/**
 * The few words the app's Markets screens need that web says through layout instead (a rail beside the chart, a
 * hover title). Everything else comes from web's own copy (`@/lib/copy`) so the two never drift.
 */
export const NATIVE_MARKETS = {
  kicker: "Solana stock markets",
  title: "Find your Window.",
  lead: "Call the next move Up or Down. Read the line and the price source before you sign.",
  sections: {
    book: { index: "01", title: "Top of book" },
    rule: { index: "02", title: "The rule" },
  },
  rule: {
    question: "Question",
    line: "The line",
    opens: "Opened",
    opensFuture: "Opens",
    lastEntry: "Calls close",
    settles: "Settles",
    source: "Price source",
    proof: "See the settlement prints",
  },
  liveVenue: "LIVE VENUE",
  network: "SOLANA DEVNET · TEST FUNDS",
  links: {
    senseiBoard: "Ask Sensei",
    sensei: "Ask Sensei about this Window",
    ticker: (asset: string) => `${asset} hub`,
  },
  livePrice: "Live",
  settlesIn: "Settles in",
  opensIn: "Opens in",
  windowGone: "Window not found",
  windowReading: "Reading the Window…",
  windowUnavailable: "Window unavailable",
  backToMarkets: "Back to Markets",
  listedLead: "Listed before the bell. A call rests at your price and fills in the first minute after the open if the book comes to you.",
  review: "Review",
  editCall: "Edit",
  confirmTitle: (side: string, asset: string, cadence: string) => `Buy ${side} on ${asset} · ${cadence}`,
  scheduleTitle: (side: string, asset: string, cadence: string) => `Schedule ${side} on ${asset} · ${cadence}`,
  quote: {
    contracts: "Contracts",
    avgPrice: "Average price",
    expected: "Expected cost",
    escrow: "Escrow held (most it can cost)",
    payout: "Pays if right",
    seat: "Refundable seat deposit",
    stake: "Stake",
    price: "Your price",
    held: "Held",
    leverage: "Leverage",
    fronted: "Reserve fronts",
    route: "Route",
    private: "Private desk",
  },
  share: "Share",
  shareImageMissing: "Sharing as text: the image card needs the next app build.",
} as const;
