[toolchain]
anchor_version = "1.2.0"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
agari_events = "cDcHZiQ1WYAHbSjxMoju86fbC8azrtQg7dzrWKynANH"

[programs.devnet]
agari_events = "cDcHZiQ1WYAHbSjxMoju86fbC8azrtQg7dzrWKynANH"

[provider]
cluster = "localnet"
wallet = "~/.config/agari/devnet/deployer.json"

[scripts]
test = "cargo test"
