[toolchain]
anchor_version = "1.2.0"
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
agari_events = "cDcHZiQ1WYAHbSjxMoju86fbC8azrtQg7dzrWKynANH"
agari_vault = "84puRVxGcjs7JNcPCVAEkkK6ZFXneEC8yky8RTMzhPi9"
agari_range = "GfsAzxPeNp2cbUTrXehHBjLjAMX6Cf69gz2zJYkGM7ha"
agari_maker = "442oD4u4fHnAwPjSqdQvkgGeDaGVEZ9YHHaLny98nEaN"
agari_parlay = "H4gdpoPirbtHP6hNdiQRLwfifjshdgDamYuvrGxj2ZCC"

[programs.devnet]
agari_events = "cDcHZiQ1WYAHbSjxMoju86fbC8azrtQg7dzrWKynANH"
agari_vault = "84puRVxGcjs7JNcPCVAEkkK6ZFXneEC8yky8RTMzhPi9"
agari_range = "GfsAzxPeNp2cbUTrXehHBjLjAMX6Cf69gz2zJYkGM7ha"
agari_maker = "442oD4u4fHnAwPjSqdQvkgGeDaGVEZ9YHHaLny98nEaN"
agari_parlay = "H4gdpoPirbtHP6hNdiQRLwfifjshdgDamYuvrGxj2ZCC"

[provider]
cluster = "localnet"
wallet = "~/.config/agari/devnet/deployer.json"

[scripts]
test = "cargo test"
